mainSections = ["post"]
rssFullContent = true   # Output page's full content in RSS.

[Sidebar] #Config for top left data
compact = false
emoji = "🚀"
subtitle1 = "\"Great things are not done by impulse, but by a series of small things brought together.\""
subtitle2 = "-Vincent Van Gogh"

[Sidebar.avatar] #This is the config for the main picture in my website
enabled = true
local = true
src = "img/avatar.jpg"

[Footer]
since = "2024"
customText = """Unless otherwise stated, all original content on this blog is licensed under the 
Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License (CC BY-NC-SA 4.0). 
You are free to share and adapt this content for non-commercial purposes, provided you give appropriate 
credit and distribute any modified content under the same license."""

[Article]
headingAnchor = false
math = false
readingTime = false

[article.license]
enabled = true
default = "Licensed under CC BY-NC-SA 4.0"

[colorScheme]
toggle = true
default = "light"

[dateFormat]
published = "Jan 02, 2006"
lastUpdated = "Jan 02, 2006 15:04 MST"
